web:
  image: 'gitlab/gitlab-ce:latest'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost:8929'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      gitlab_rails['initial_root_password'] = "password"
      prometheus_monitoring['enable'] = false
  ports:
    - '8929:8929'
    - '2224:22'
  volumes:
    - 'data_config:/etc/gitlab'
    - 'data_logs:/var/log/gitlab'
    - 'data_data:/var/opt/gitlab'